services:
  db:
    image: postgres:16
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: diabetes_app_user
      # This line now securely reads the password from your .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: diabetes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

